default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DB_CONN_POOL_MAX_SIZE"] || 5 %>
  timeout: 5000

development:
  <<: *default
  username: <%= `whoami` %>
  database: caseflow_feedback_development

demo:
  <<: *default
  url: <%= ENV["POSTGRES_URL"] %>

test:
  <<: *default
  username: <%= `whoami` %>
  database: caseflow_feedback_test

production:
  <<: *default
  url: <%= ENV["POSTGRES_URL"] %>
